### ISSUE TITLE
Create an executable versione of the program.

### ISSUE THREAD

**Issue by francescorinaldi** [francescorinaldi/MMs_Simulator#4]
We need to create a runnable / executable versione of the program.

**Comment by francescorinaldi** [comment]
To be executable, the program also needs to read these three other files: traccia10seconds.txt, vmOnDemand_eu-west-1_linux_.xml and vmReserved_eu-west-1_linux_c1-xlarge.xml.

The first solution was just putting in the same folder the Jar created with the three files mentioned above, but it could be uncomfortable for the user, and it was for sure a non-professional solution.

For this reason we tried to "assemble" into the jar also these resources. Now we need to modify the code in order to properly let the program access to these files.

**Comment by giancarlocolaci** [comment]
To avoid the risk that a resource was not found during the execution, we changed the File operations with the InputStream operations:

InputStream in = getClass().getResourceAsStream("traccia10seconds.txt");
br = new BufferedReader(new InputStreamReader(in));

InputStream iSXml = XMLparser.class.getResourceAsStream("vmOnDemand_eu-west-1_linux_.xml");
DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
Document doc = dBuilder.parse(iSXml);

InputStream iSXml = XMLparser.class.getResourceAsStream("vmReserved_eu-west-1_linux_c1-xlarge.xml");
DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
Document doc = dBuilder.parse(iSXml);
